# Use the ollama/ollama base image
FROM ollama/ollama

# Set the working directory to /root/.ollama/
WORKDIR /root/.ollama/

# Copy all files from the local ollama_files directory to /root/.ollama/ in the container
COPY ollama_files/ /root/.ollama/